export const strverSheet =  [
        {
            "step_no": 1,
            "head_step_no": "Arrays and Hashing",
            "topics": [
                {
                    "id": "nxtprmttin",
                    "step_no": 1,
                    "sl_no_in_step": 1,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Next Permutation",
                    "post_link": "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/",
                    "yt_link": "https://youtu.be/JDOXKqF60RQ",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/next-greater-permutation_6929564?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3dug78u",
                    "lc_link": "https://leetcode.com/problems/next-permutation/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"}]"
                },
                {
                    "id": "3smprblm",
                    "step_no": 1,
                    "sl_no_in_step": 2,
                    "head_step_no": "Arrays and Hashing",
                    "title": "3-Sum Problem",
                    "post_link": "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/",
                    "yt_link": "https://youtu.be/DhFh8Kw7ymk",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/three-sum_6922132?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3C9uTvQ",
                    "lc_link": "https://leetcode.com/problems/3sum/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"sorting\",\"label\":\"Sorting\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"hashing\",\"label\":\"Hashing\"}]"
                },
                {
                    "id": "kdnslgrithm",
                    "step_no": 1,
                    "sl_no_in_step": 3,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Kadane's Algorithm",
                    "post_link": "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",
                    "yt_link": "https://youtu.be/AHZpyENo7k4",
                    "cs_link": "https://bit.ly/3HZltTa",
                    "gfg_link": null,
                    "lc_link": "https://leetcode.com/problems/maximum-subarray/",
                    "company_tags": null,
                    "difficulty": 0,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "mjritylmntn3tims",
                    "step_no": 1,
                    "sl_no_in_step": 4,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Majority Element (n/3 times)",
                    "post_link": "https://takeuforward.org/data-structure/majority-elementsn-3-times-find-the-elements-that-appears-more-than-n-3-times-in-the-array/",
                    "yt_link": "https://youtu.be/vwZj1K0e9U8",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/majority-element_6915220?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": null,
                    "lc_link": "https://leetcode.com/problems/majority-element-ii/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "cntnmbrfsbrryswithgivnxrk",
                    "step_no": 1,
                    "sl_no_in_step": 5,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Count number of subarrays with given xor K",
                    "post_link": "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/",
                    "yt_link": "https://youtu.be/eZr-6p0B7ME",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/subarrays-with-xor-k_6826258?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3PrvhZs",
                    "lc_link": "https://www.interviewbit.com/problems/subarray-with-given-xor/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "findthrptingndmissingnmbr-i",
                    "step_no": 1,
                    "sl_no_in_step": 6,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Find the repeating and missing number",
                    "post_link": "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/",
                    "yt_link": "https://youtu.be/2D0D8HE6uak",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/missing-and-repeating-numbers_6828164?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3zWZoCs",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"maths\",\"label\":\"Maths\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "cntinvrsins",
                    "step_no": 1,
                    "sl_no_in_step": 7,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Count Inversions",
                    "post_link": "https://takeuforward.org/data-structure/count-inversions-in-an-array/",
                    "yt_link": "https://youtu.be/AseUmwVNaoY",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/number-of-inversions_6840276?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3PtLWLM",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"sorting\",\"label\":\"Sorting\"},{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "mximmprdctsbrry",
                    "step_no": 1,
                    "sl_no_in_step": 8,
                    "head_step_no": "Arrays and Hashing",
                    "title": "Maximum Product Subarray",
                    "post_link": "https://takeuforward.org/data-structure/maximum-product-subarray-in-an-array/",
                    "yt_link": "https://youtu.be/hnswaLJvr6g",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/subarray-with-maximum-product_6890008?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3PrlQsU",
                    "lc_link": "https://leetcode.com/problems/maximum-product-subarray/",
                    "company_tags": null,
                    "difficulty": 0,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 2,
            "head_step_no": "Binary Search",
            "topics": [
                {
                    "id": "srchinrttdsrtdrryii",
                    "step_no": 2,
                    "sl_no_in_step": 1,
                    "head_step_no": "Binary Search",
                    "title": "Search in Rotated Sorted Array II",
                    "post_link": "https://takeuforward.org/arrays/search-element-in-rotated-sorted-array-ii/",
                    "yt_link": "https://youtu.be/w2G2W8l__pc",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/search-in-a-rotated-sorted-array-ii_7449547?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Rm85Nb",
                    "lc_link": "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"}]"
                },
                {
                    "id": "findminimminrttdsrtdrry",
                    "step_no": 2,
                    "sl_no_in_step": 2,
                    "head_step_no": "Binary Search",
                    "title": "Find minimum in Rotated Sorted Array",
                    "post_link": "https://takeuforward.org/data-structure/minimum-in-rotated-sorted-array/",
                    "yt_link": "https://youtu.be/nhEMDKMB44g",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/rotated-array_1093219?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Az1OJ3",
                    "lc_link": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "findpklmnt",
                    "step_no": 2,
                    "sl_no_in_step": 3,
                    "head_step_no": "Binary Search",
                    "title": "Find peak element",
                    "post_link": "https://takeuforward.org/data-structure/peak-element-in-array/",
                    "yt_link": "https://youtu.be/cXxmbemS6XM",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/find-peak-element_1081482?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Apsuf3",
                    "lc_link": "https://leetcode.com/problems/find-peak-element/#:~:text=Find%20Peak%20Element%20%2D%20LeetCode&text=A%20peak%20element%20is%20an,to%20any%20of%20the%20peaks.",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"}]"
                },
                {
                    "id": "kktingbnns",
                    "step_no": 2,
                    "sl_no_in_step": 4,
                    "head_step_no": "Binary Search",
                    "title": "Koko Eating Bananas",
                    "post_link": "https://takeuforward.org/binary-search/koko-eating-bananas/",
                    "yt_link": "https://youtu.be/qyfekrNni90",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/minimum-rate-to-eat-bananas_7449064?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3LSY491",
                    "lc_link": "https://leetcode.com/problems/koko-eating-bananas/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "ggrssivcws",
                    "step_no": 2,
                    "sl_no_in_step": 5,
                    "head_step_no": "Binary Search",
                    "title": "Aggressive Cows",
                    "post_link": "https://takeuforward.org/data-structure/aggressive-cows-detailed-solution/",
                    "yt_link": "https://youtu.be/R_Mfw4ew-Vo",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/aggressive-cows_1082559?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3rBuE5Z",
                    "lc_link": "https://www.spoj.com/problems/AGGRCOW/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "bkllctinprblm",
                    "step_no": 2,
                    "sl_no_in_step": 6,
                    "head_step_no": "Binary Search",
                    "title": "Book Allocation Problem",
                    "post_link": "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/",
                    "yt_link": "https://youtu.be/Z0hwjftStI4",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/allocate-books_1090540?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QMrMxP",
                    "lc_link": "https://bit.ly/3MZQOct",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"}]"
                },
                {
                    "id": "mdinf2srtdrrys",
                    "step_no": 2,
                    "sl_no_in_step": 7,
                    "head_step_no": "Binary Search",
                    "title": "Median of 2 sorted arrays",
                    "post_link": "https://takeuforward.org/data-structure/median-of-two-sorted-arrays-of-different-sizes/",
                    "yt_link": "https://youtu.be/C2rRzz-JDk8",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/median-of-two-sorted-arrays_985294?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QPi7Xp",
                    "lc_link": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "minimizmxdistnctgssttin",
                    "step_no": 2,
                    "sl_no_in_step": 8,
                    "head_step_no": "Binary Search",
                    "title": "Minimize Max Distance to Gas Station",
                    "post_link": "https://takeuforward.org/arrays/minimise-maximum-distance-between-gas-stations/",
                    "yt_link": "https://www.youtube.com/watch?v=kMSBvlZ-_HA&list=PLgUwDviBIf0pMFMWuuvDNMAkoQFi-h0ZF&index=21",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/minimise-max-distance_7541449?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3s40ybG",
                    "lc_link": "https://leetcode.com/problems/minimize-max-distance-to-gas-station/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 3,
            "head_step_no": "Linked List",
            "topics": [
                {
                    "id": "middlflinkdlisttrtishrmthd",
                    "step_no": 3,
                    "sl_no_in_step": 1,
                    "head_step_no": "Linked List",
                    "title": "Middle of a LinkedList [TortoiseHare Method]",
                    "post_link": "https://takeuforward.org/data-structure/find-middle-element-in-a-linked-list/",
                    "yt_link": "https://youtu.be/7LjQ57RqgEc?si=ir_rRDio38rhamU_",
                    "cs_link": "https://www.codingninjas.com/studio/problems/middle-of-linked-list_973250?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3dAjkn1",
                    "lc_link": "https://leetcode.com/problems/middle-of-the-linked-list/",
                    "company_tags": null,
                    "difficulty": 0,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "dtctlpinll",
                    "step_no": 3,
                    "sl_no_in_step": 2,
                    "head_step_no": "Linked List",
                    "title": "Detect a loop in LL",
                    "post_link": "https://takeuforward.org/data-structure/detect-a-cycle-in-a-linked-list/",
                    "yt_link": "https://youtu.be/wiOo4DC5GGA?si=zagt6O6tFXc4_3cx",
                    "cs_link": "https://www.codingninjas.com/studio/problems/cycle-detection-in-a-singly-linked-list_628974?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QN8PLn",
                    "lc_link": "https://leetcode.com/problems/linked-list-cycle/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "rmvnthndfrmthbckfthll",
                    "step_no": 3,
                    "sl_no_in_step": 3,
                    "head_step_no": "Linked List",
                    "title": "Remove Nth node from the back of the LL",
                    "post_link": "https://takeuforward.org/data-structure/remove-n-th-node-from-the-end-of-a-linked-list/",
                    "yt_link": "https://youtu.be/3kMKYQ2wNIU?si=DtFDnPU7z9HMz_GM",
                    "cs_link": "https://www.codingninjas.com/studio/problems/delete-kth-node-from-end_799912?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3pobNKM",
                    "lc_link": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "findthintrsctinpintfyll",
                    "step_no": 3,
                    "sl_no_in_step": 4,
                    "head_step_no": "Linked List",
                    "title": "Find the intersection point of Y LL",
                    "post_link": "https://takeuforward.org/data-structure/find-intersection-of-two-linked-lists/",
                    "yt_link": "https://youtu.be/0DYoPz2Tpt4?si=L-uJs5yXUxj4VJM2",
                    "cs_link": "https://www.codingninjas.com/studio/problems/-intersection-of-two-linked-lists_630457?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3pl5R4W",
                    "lc_link": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "srtll",
                    "step_no": 3,
                    "sl_no_in_step": 5,
                    "head_step_no": "Linked List",
                    "title": "Sort LL",
                    "post_link": "https://takeuforward.org/linked-list/sort-a-linked-list",
                    "yt_link": "https://youtu.be/8ocB7a_c-Cc?si=Gv-Y8q8-WyARoV35",
                    "cs_link": "https://www.codingninjas.com/studio/problems/sort-linked-list_625193?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3dDuLdO",
                    "lc_link": "https://leetcode.com/problems/sort-list/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "sgrrgtddndvnndsinll",
                    "step_no": 3,
                    "sl_no_in_step": 6,
                    "head_step_no": "Linked List",
                    "title": "Segrregate odd and even nodes in LL",
                    "post_link": "https://takeuforward.org/data-structure/segregate-even-and-odd-nodes-in-linkedlist",
                    "yt_link": "https://youtu.be/qf6qp7GzD5Q?si=JozAyXUdT8EJMSCQ",
                    "cs_link": "https://www.codingninjas.com/studio/problems/segregate-even-and-odd-nodes-in-a-linked-list_1116100?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3A3aeqe",
                    "lc_link": "https://leetcode.com/problems/odd-even-linked-list/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 4,
            "head_step_no": "Recursion and Backtracking",
            "topics": [
                {
                    "id": "printllsbsqncspwrst",
                    "step_no": 4,
                    "sl_no_in_step": 1,
                    "head_step_no": "Recursion and Backtracking",
                    "title": "Print all subsequences/Power Set",
                    "post_link": "https://takeuforward.org/data-structure/power-set-print-all-the-possible-subsequences-of-the-string/",
                    "yt_link": "https://youtu.be/b7AYbpM5YrE",
                    "cs_link": "https://www.codingninjas.com/studio/problems/print-subsequences_8416366?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3STXz1t",
                    "lc_link": "https://leetcode.com/problems/subsets/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"recursion\",\"label\":\"Recursion\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "cmbintinsm",
                    "step_no": 4,
                    "sl_no_in_step": 2,
                    "head_step_no": "Recursion and Backtracking",
                    "title": "Combination Sum",
                    "post_link": "https://takeuforward.org/data-structure/combination-sum-1/",
                    "yt_link": "https://www.youtube.com/watch?v=OyZFFqQtu98&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=49",
                    "cs_link": "https://www.codingninjas.com/studio/problems/combination-sum_981296?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3C9bJ91",
                    "lc_link": "https://leetcode.com/problems/combination-sum/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"recursion\",\"label\":\"Recursion\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"arrays\",\"label\":\"Arrays\"}]"
                },
                {
                    "id": "nqn",
                    "step_no": 4,
                    "sl_no_in_step": 3,
                    "head_step_no": "Recursion and Backtracking",
                    "title": "N Queen",
                    "post_link": "https://takeuforward.org/data-structure/n-queen-problem-return-all-distinct-solutions-to-the-n-queens-puzzle/",
                    "yt_link": "https://www.youtube.com/watch?v=i05Ju7AftcM&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=57",
                    "cs_link": "https://www.codingninjas.com/studio/problems/n-queens_696453?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QurLP8",
                    "lc_link": "https://leetcode.com/problems/n-queens/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                },
                {
                    "id": "sdkslvr",
                    "step_no": 4,
                    "sl_no_in_step": 4,
                    "head_step_no": "Recursion and Backtracking",
                    "title": "Sudoko Solver",
                    "post_link": "https://takeuforward.org/data-structure/sudoku-solver/",
                    "yt_link": "https://www.youtube.com/watch?v=FWAIf_EVUKE&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=58",
                    "cs_link": "https://www.codingninjas.com/studio/problems/sudoku-solver_8416969?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3PrA5hs",
                    "lc_link": "https://leetcode.com/problems/sudoku-solver/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "mclringprblm",
                    "step_no": 4,
                    "sl_no_in_step": 5,
                    "head_step_no": "Recursion and Backtracking",
                    "title": "M Coloring Problem",
                    "post_link": "https://takeuforward.org/data-structure/m-coloring-problem/",
                    "yt_link": "https://www.youtube.com/watch?v=wuVwUK25Rfc&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=59",
                    "cs_link": "https://www.codingninjas.com/studio/problems/m-coloring-problem_981273?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Cepqnv",
                    "lc_link": "https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1#",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "wrdsrch",
                    "step_no": 4,
                    "sl_no_in_step": 6,
                    "head_step_no": "Recursion and Backtracking",
                    "title": "Word Search",
                    "post_link": "https://takeuforward.org/data-structure/word-search-leetcode/",
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/studio/problems/word-search---l_892986?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Ca9xOL",
                    "lc_link": "https://leetcode.com/problems/word-search/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"string\",\"label\":\"String\"}]"
                }
            ]
        },
        {
            "step_no": 5,
            "head_step_no": "Stacks/Queues",
            "topics": [
                {
                    "id": "nxtgrtrlmnt",
                    "step_no": 5,
                    "sl_no_in_step": 1,
                    "head_step_no": "Stacks/Queues",
                    "title": "Next Greater Element",
                    "post_link": "https://takeuforward.org/data-structure/next-greater-element-using-stack/",
                    "yt_link": "https://youtu.be/e7XQLtOQM3I?si=QdcHpTtx6gAHsext",
                    "cs_link": "https://www.codingninjas.com/studio/problems/next-greater-element_670312?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QNPQAs",
                    "lc_link": "https://leetcode.com/problems/next-greater-element-i/",
                    "company_tags": null,
                    "difficulty": 0,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"stack\",\"label\":\"Stack\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "trppingrinwtr",
                    "step_no": 5,
                    "sl_no_in_step": 2,
                    "head_step_no": "Stacks/Queues",
                    "title": "Trapping Rainwater",
                    "post_link": "https://takeuforward.org/data-structure/trapping-rainwater/",
                    "yt_link": "https://youtu.be/1_5VuquLbXg?si=NFG6df318_6OtGvg",
                    "cs_link": "https://www.codingninjas.com/studio/problems/trapping-rain-water_630519?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3AqMa1W",
                    "lc_link": "https://leetcode.com/problems/trapping-rain-water/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"stack\",\"label\":\"Stack\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lrgstrctnglinhistgrm",
                    "step_no": 5,
                    "sl_no_in_step": 3,
                    "head_step_no": "Stacks/Queues",
                    "title": "Largest rectangle in a histogram",
                    "post_link": "https://takeuforward.org/data-structure/area-of-largest-rectangle-in-histogram/",
                    "yt_link": "https://youtu.be/Bzat9vgD0fs?si=DiBlLejXcr6EJoyB",
                    "cs_link": "https://www.codingninjas.com/studio/problems/largest-rectangle-in-a-histogram_1058184?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3AnVYd5",
                    "lc_link": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "stridcllisin",
                    "step_no": 5,
                    "sl_no_in_step": 4,
                    "head_step_no": "Stacks/Queues",
                    "title": "Asteroid Collision",
                    "post_link": "",
                    "yt_link": "https://youtu.be/_eYGqw_VDR4?si=YyxibcHq800RqgIQ",
                    "cs_link": "https://www.codingninjas.com/studio/problems/asteroid-collision_977232?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Tpi0Tw",
                    "lc_link": "https://leetcode.com/problems/asteroid-collision/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"stack\",\"label\":\"Stack\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "slidingwindwmximm",
                    "step_no": 5,
                    "sl_no_in_step": 5,
                    "head_step_no": "Stacks/Queues",
                    "title": "Sliding Window maximum",
                    "post_link": "https://takeuforward.org/data-structure/sliding-window-maximum/",
                    "yt_link": "https://youtu.be/NwBvene4Imo?si=eU1PY-bcQfk5wdog",
                    "cs_link": "https://www.codingninjas.com/studio/problems/sliding-maximum-_701652?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3w7SSri",
                    "lc_link": "https://leetcode.com/problems/sliding-window-maximum/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"queue\",\"label\":\"Queue\"},{\"value\":\"heap\",\"label\":\"Heap\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lrcchimprtnt",
                    "step_no": 5,
                    "sl_no_in_step": 6,
                    "head_step_no": "Stacks/Queues",
                    "title": "LRU cache (IMPORTANT)",
                    "post_link": "https://takeuforward.org/data-structure/implement-lru-cache/",
                    "yt_link": "https://youtu.be/z9bJUPxzFOw?si=IUo_d35rXBD0CBAF",
                    "cs_link": "https://www.codingninjas.com/studio/problems/lru-cache-implementation_670276?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3zZneNN",
                    "lc_link": "https://leetcode.com/problems/lru-cache/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"linked-list\",\"label\":\"Linked List\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 6,
            "head_step_no": "Heaps",
            "topics": [
                {
                    "id": "kthlrgstlmntinnrrysprirityq",
                    "step_no": 6,
                    "sl_no_in_step": 1,
                    "head_step_no": "Heaps",
                    "title": "Kth largest element in an array [use priority queue]",
                    "post_link": "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-an-array/",
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/k-largest-elements_796005?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Avss5k",
                    "lc_link": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
                    "company_tags": null,
                    "difficulty": 0,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"heap\",\"label\":\"Heap\"}]"
                },
                {
                    "id": "tskschdlr",
                    "step_no": 6,
                    "sl_no_in_step": 2,
                    "head_step_no": "Heaps",
                    "title": "Task Scheduler",
                    "post_link": null,
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/studio/problems/task-scheduler_1070424?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3h2Z92Z",
                    "lc_link": "https://leetcode.com/problems/task-scheduler/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"greedy\",\"label\":\"Greedy\"},{\"value\":\"sorting\",\"label\":\"Sorting\"},{\"value\":\"heap\",\"label\":\"Heap\"}]"
                },
                {
                    "id": "minhpndmxhpimplmnttin",
                    "step_no": 6,
                    "sl_no_in_step": 3,
                    "head_step_no": "Heaps",
                    "title": "Min Heap and Max Heap Implementation",
                    "post_link": null,
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/studio/problems/min-heap-implementation_5480527?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3weGgP3",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"heap\",\"label\":\"Heap\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 7,
            "head_step_no": "Trees (BT + BST)",
            "topics": [
                {
                    "id": "dimtrfbinrytr",
                    "step_no": 7,
                    "sl_no_in_step": 1,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Diameter of Binary Tree",
                    "post_link": "https://takeuforward.org/data-structure/calculate-the-diameter-of-a-binary-tree/",
                    "yt_link": "https://youtu.be/Rezetez59Nk",
                    "cs_link": "https://www.codingninjas.com/studio/problems/diameter-of-binary-tree_920552?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3wcfG9l",
                    "lc_link": "https://leetcode.com/problems/diameter-of-binary-tree/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "mximmpthsm",
                    "step_no": 7,
                    "sl_no_in_step": 2,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Maximum path sum",
                    "post_link": "https://takeuforward.org/data-structure/maximum-sum-path-in-binary-tree/",
                    "yt_link": "https://youtu.be/WszrfSwMz58",
                    "cs_link": "https://www.codingninjas.com/studio/problems/maximum-sum-path-of-a-binary-tree._1214968?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QAFjbW",
                    "lc_link": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "bttmviwfbinrytr",
                    "step_no": 7,
                    "sl_no_in_step": 3,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Bottom View of Binary Tree",
                    "post_link": "https://takeuforward.org/data-structure/bottom-view-of-a-binary-tree/",
                    "yt_link": "https://youtu.be/0FtVY6I4pB8",
                    "cs_link": "https://www.codingninjas.com/studio/problems/bottom-view-of-binary-tree_893110?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3Asftl0",
                    "lc_link": "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lcinbinrytr",
                    "step_no": 7,
                    "sl_no_in_step": 4,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "LCA in Binary Tree",
                    "post_link": "https://takeuforward.org/data-structure/lowest-common-ancestor-for-two-given-nodes/",
                    "yt_link": "https://youtu.be/_-QHfMDde90",
                    "cs_link": "https://www.codingninjas.com/studio/problems/lca-of-binary-tree_920541?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3popvgG",
                    "lc_link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"binary-search-tree\",\"label\":\"Binary Search Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "minimmtimtkntbrnthbinrytrfrmnd",
                    "step_no": 7,
                    "sl_no_in_step": 5,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Minimum time taken to BURN the Binary Tree from a Node",
                    "post_link": null,
                    "yt_link": "https://youtu.be/2r5wLmQfD6g",
                    "cs_link": "https://www.codingninjas.com/studio/problems/time-to-burn-tree_1469067?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3wcg7k1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "cnstrctbinrytrfrminrdrndprrdr",
                    "step_no": 7,
                    "sl_no_in_step": 6,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Construct Binary Tree from inorder and preorder",
                    "post_link": "https://takeuforward.org/data-structure/construct-a-binary-tree-from-inorder-and-preorder-traversal/",
                    "yt_link": "https://youtu.be/aZNaLrVebKQ",
                    "cs_link": "https://www.codingninjas.com/studio/problems/construct-binary-tree-from-inorder-and-preorder-traversal_920539?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3AoZ4N5",
                    "lc_link": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "mrrisprrdrtrvrslfbinrytr",
                    "step_no": 7,
                    "sl_no_in_step": 7,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Morris Preorder Traversal of a Binary Tree",
                    "post_link": "https://takeuforward.org/data-structure/morris-preorder-traversal-of-a-binary-tree/",
                    "yt_link": "https://youtu.be/80Zug6D1_r4",
                    "cs_link": "https://www.codingninjas.com/studio/problems/preorder-binary-tree_5948?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3EORTB9",
                    "lc_link": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "dltndinbinrysrchtr",
                    "step_no": 7,
                    "sl_no_in_step": 8,
                    "head_step_no": null,
                    "title": "Delete a Node in Binary Search Tree",
                    "post_link": null,
                    "yt_link": "https://youtu.be/kouxiP_H5WE",
                    "cs_link": "https://www.codingninjas.com/studio/problems/delete-node-in-bst_920381?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/delete-a-node-from-bst/1",
                    "lc_link": "https://leetcode.com/problems/delete-node-in-a-bst/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"binary-search-tree\",\"label\":\"Binary Search Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lcinbinrysrchtr",
                    "step_no": 7,
                    "sl_no_in_step": 9,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "LCA in Binary Search Tree",
                    "post_link": null,
                    "yt_link": "https://youtu.be/cX_kPV_foZc",
                    "cs_link": null,
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1",
                    "lc_link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"binary-search-tree\",\"label\":\"Binary Search Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "twsminbstchckifthrxistspirwithsmk",
                    "step_no": 7,
                    "sl_no_in_step": 10,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Two Sum In BST | Check if there exists a pair with Sum K",
                    "post_link": null,
                    "yt_link": "https://youtu.be/ssL3sHwPeb4",
                    "cs_link": "https://www.codingninjas.com/studio/problems/pair-sum-in-bst._920493?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/find-a-pair-with-given-target-in-bst/1",
                    "lc_link": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"},{\"value\":\"binary-search-tree\",\"label\":\"Binary Search Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lrgstbstinbinrytr",
                    "step_no": 7,
                    "sl_no_in_step": 11,
                    "head_step_no": "Trees (BT + BST)",
                    "title": "Largest BST in Binary Tree",
                    "post_link": null,
                    "yt_link": "https://youtu.be/X0oXMdtUDwo",
                    "cs_link": "https://www.codingninjas.com/studio/problems/size-of-largest-bst-in-binary-tree_893103?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/largest-bst/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"binary-search-tree\",\"label\":\"Binary Search Tree\"},{\"value\":\"binary-tree\",\"label\":\"Binary Tree\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 8,
            "head_step_no": "Graphs",
            "topics": [
                {
                    "id": "rttnrngs",
                    "step_no": 8,
                    "sl_no_in_step": 1,
                    "head_step_no": "Graphs",
                    "title": "Rotten Oranges",
                    "post_link": "https://takeuforward.org/data-structure/rotten-oranges-min-time-to-rot-all-oranges-bfs/",
                    "yt_link": "https://www.youtube.com/watch?v=yf3oUhkvqA0",
                    "cs_link": "https://www.codingninjas.com/studio/problems/rotting-oranges_701655?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3R4htWb",
                    "lc_link": "https://leetcode.com/problems/rotting-oranges/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"stack\",\"label\":\"Stack\"},{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "wrdlddr1",
                    "step_no": 8,
                    "sl_no_in_step": 2,
                    "head_step_no": "Graphs",
                    "title": "Word ladder - 1",
                    "post_link": "https://takeuforward.org/graph/word-ladder-i-g-29/",
                    "yt_link": "https://youtu.be/tRPda0rcf8E",
                    "cs_link": "https://www.codingninjas.com/studio/problems/word-ladder_1102319?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/word-ladder/1",
                    "lc_link": "https://leetcode.com/problems/word-ladder/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"string\",\"label\":\"String\"}]"
                },
                {
                    "id": "nmbrfdistinctislndsdfsmltisrc",
                    "step_no": 8,
                    "sl_no_in_step": 3,
                    "head_step_no": "Graphs",
                    "title": "Number of Distinct Islands [dfs multisource]",
                    "post_link": "https://takeuforward.org/data-structure/number-of-islands/",
                    "yt_link": "https://youtu.be/muncqlKJrH0",
                    "cs_link": "https://www.codingninjas.com/studio/problems/distinct-islands_630460?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/number-of-distinct-islands/1",
                    "lc_link": "https://leetcode.com/problems/number-of-distinct-islands-ii/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "crsschdlii",
                    "step_no": 8,
                    "sl_no_in_step": 4,
                    "head_step_no": "Graphs",
                    "title": "Course Schedule - II",
                    "post_link": "https://takeuforward.org/data-structure/course-schedule-i-and-ii-pre-requisite-tasks-topological-sort-g-24/",
                    "yt_link": "https://youtu.be/WAOfKpxYHR8",
                    "cs_link": "https://www.codingninjas.com/studio/problems/course-schedule-ii_1069243?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3w8ZBBl",
                    "lc_link": "https://leetcode.com/problems/course-schedule-ii/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lindictinry",
                    "step_no": 8,
                    "sl_no_in_step": 5,
                    "head_step_no": "Graphs",
                    "title": "Alien dictionary",
                    "post_link": "https://takeuforward.org/data-structure/alien-dictionary-topological-sort-g-26/",
                    "yt_link": "https://youtu.be/U3N_je7tWAs",
                    "cs_link": "https://www.codingninjas.com/studio/problems/alien-dictionary_630423?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/alien-dictionary/1",
                    "lc_link": "https://leetcode.com/problems/alien-dictionary/solution/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "djisktrslgrithm",
                    "step_no": 8,
                    "sl_no_in_step": 6,
                    "head_step_no": "Graphs",
                    "title": "Djisktra's Algorithm",
                    "post_link": "https://takeuforward.org/data-structure/dijkstras-algorithm-using-set-g-33/",
                    "yt_link": "https://www.youtube.com/watch?v=rp1SMw7HSO8&list=PLgUwDviBIf0oE3gA41TKO2H5bHpPd7fzn&index=35",
                    "cs_link": "https://www.codingninjas.com/studio/problems/dijkstra's-shortest-path_985358?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "chpstflightswithinkstps",
                    "step_no": 8,
                    "sl_no_in_step": 7,
                    "head_step_no": "Graphs",
                    "title": "Cheapest flights within k stops",
                    "post_link": "https://takeuforward.org/data-structure/g-38-cheapest-flights-within-k-stops/",
                    "yt_link": "https://youtu.be/9XybHVqTHcQ",
                    "cs_link": "https://www.codingninjas.com/studio/problems/saving-money_1171195?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3OnPWi4",
                    "lc_link": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "bllmnfrdlgrithm",
                    "step_no": 8,
                    "sl_no_in_step": 8,
                    "head_step_no": "Graphs",
                    "title": "Bellman Ford Algorithm",
                    "post_link": "https://takeuforward.org/data-structure/bellman-ford-algorithm-g-41/",
                    "yt_link": "https://youtu.be/0vVofAhAYjc",
                    "cs_link": "https://www.codingninjas.com/studio/problems/bellman-ford_2041977?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "flydwrshllgrithm",
                    "step_no": 8,
                    "sl_no_in_step": 9,
                    "head_step_no": "Graphs",
                    "title": "Floyd Warshal Algorithm",
                    "post_link": "https://takeuforward.org/data-structure/floyd-warshall-algorithm-g-42/",
                    "yt_link": "https://youtu.be/YbY8cVwWAvw",
                    "cs_link": "https://www.codingninjas.com/studio/problems/floyd-warshall_2041979?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "krsklslgrithm",
                    "step_no": 8,
                    "sl_no_in_step": 10,
                    "head_step_no": "Graphs",
                    "title": "Kruskal's Algorithm",
                    "post_link": "https://takeuforward.org/data-structure/kruskals-algorithm-minimum-spanning-tree-g-47/",
                    "yt_link": "https://youtu.be/DMnDM_sxVig",
                    "cs_link": "https://www.codingninjas.com/studio/problems/kruskal’s-minimum-spanning-tree-algorithm_1082553?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "ccntsmrg",
                    "step_no": 8,
                    "sl_no_in_step": 11,
                    "head_step_no": "Graphs",
                    "title": "Accounts merge",
                    "post_link": "https://takeuforward.org/data-structure/accounts-merge-dsu-g-50/",
                    "yt_link": "https://youtu.be/FMwpt_aQOGw",
                    "cs_link": "https://www.codingninjas.com/studio/problems/accounts-merge_1089558?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/merging-details/1",
                    "lc_link": "https://leetcode.com/problems/accounts-merge/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "bridgsingrph",
                    "step_no": 8,
                    "sl_no_in_step": 12,
                    "head_step_no": "Graphs",
                    "title": "Bridges in Graph",
                    "post_link": "https://takeuforward.org/graph/bridges-in-graph-using-tarjans-algorithm-of-time-in-and-low-time-g-55/",
                    "yt_link": "https://youtu.be/qrAub5z8FeA",
                    "cs_link": "https://www.codingninjas.com/studio/problems/bridges-in-a-graph_893026?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3dFdvVe",
                    "lc_link": "https://leetcode.com/problems/critical-connections-in-a-network/discuss/382385/find-bridges-in-a-graph",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"graph\",\"label\":\"Graph\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 9,
            "head_step_no": "Dynamic Programming",
            "topics": [
                {
                    "id": "mximmsmfnndjcntlmntsdp5",
                    "step_no": 9,
                    "sl_no_in_step": 1,
                    "head_step_no": "Dynamic Programming",
                    "title": "Maximum sum of non-adjacent elements (DP 5)",
                    "post_link": "https://takeuforward.org/data-structure/maximum-sum-of-non-adjacent-elements-dp-5/",
                    "yt_link": "https://www.youtube.com/watch?v=GrMBfJNk_NY",
                    "cs_link": "https://www.codingninjas.com/studio/problems/maximum-sum-of-non-adjacent-elements_843261?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3QOMRs1",
                    "lc_link": "https://leetcode.com/problems/house-robber/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"recursion\",\"label\":\"Recursion\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"}]"
                },
                {
                    "id": "ninjstriningdp7",
                    "step_no": 9,
                    "sl_no_in_step": 2,
                    "head_step_no": "Dynamic Programming",
                    "title": "Ninja's Training (DP 7)",
                    "post_link": "https://takeuforward.org/data-structure/dynamic-programming-ninjas-training-dp-7/",
                    "yt_link": "https://www.youtube.com/watch?v=AE39gJYuRog",
                    "cs_link": "https://www.codingninjas.com/studio/problems/ninja’s-training_3621003?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3glc9kp",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                },
                {
                    "id": "minimmpthsmingriddp10",
                    "step_no": 9,
                    "sl_no_in_step": 3,
                    "head_step_no": "Dynamic Programming",
                    "title": "Minimum path sum in Grid (DP 10)",
                    "post_link": "https://takeuforward.org/data-structure/minimum-path-sum-in-a-grid-dp-10/",
                    "yt_link": "https://www.youtube.com/watch?v=_rgTlyky1uQ",
                    "cs_link": "https://www.codingninjas.com/studio/problems/minimum-path-sum_985349?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3c1H9Uf",
                    "lc_link": "https://leetcode.com/problems/minimum-path-sum/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"recursion\",\"label\":\"Recursion\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "sbstsmqlttrgtdp14",
                    "step_no": 9,
                    "sl_no_in_step": 4,
                    "head_step_no": "Dynamic Programming",
                    "title": "Subset sum equal to target (DP- 14)",
                    "post_link": "https://takeuforward.org/data-structure/subset-sum-equal-to-target-dp-14/",
                    "yt_link": "https://www.youtube.com/watch?v=fWX9xDmIzRI",
                    "cs_link": "https://www.codingninjas.com/studio/problems/subset-sum-equal-to-k_1550954?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                },
                {
                    "id": "01knpsckdp19",
                    "step_no": 9,
                    "sl_no_in_step": 5,
                    "head_step_no": "Dynamic Programming",
                    "title": "Assign Cookies",
                    "post_link": "",
                    "yt_link": "https://youtu.be/DIX2p7vb9co?si=6G7JzMZ2TSP_LWSG",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/assign-cookies_8390826?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1",
                    "lc_link": "https://leetcode.com/problems/assign-cookies/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"recursion\",\"label\":\"Recursion\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "rdcttingprblmdp24",
                    "step_no": 9,
                    "sl_no_in_step": 6,
                    "head_step_no": "Dynamic Programming",
                    "title": "Rod Cutting Problem | (DP - 24)",
                    "post_link": "https://takeuforward.org/data-structure/rod-cutting-problem-dp-24/",
                    "yt_link": "https://youtu.be/mO8XpGoJwuo",
                    "cs_link": "https://www.codingninjas.com/studio/problems/rod-cutting-problem_800284?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/rod-cutting0840/1",
                    "lc_link": null,
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                },
                {
                    "id": "lngstcmmnsbsqnc",
                    "step_no": 9,
                    "sl_no_in_step": 7,
                    "head_step_no": "Dynamic Programming",
                    "title": "Longest Common Subsequence",
                    "post_link": "https://takeuforward.org/data-structure/longest-common-subsequence-dp-25/",
                    "yt_link": "https://youtu.be/NPZn9jBrX8U",
                    "cs_link": "https://bit.ly/3raZbqM",
                    "gfg_link": null,
                    "lc_link": "https://leetcode.com/problems/longest-common-subsequence/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "lngstplindrmicsbsqncdp28",
                    "step_no": 9,
                    "sl_no_in_step": 8,
                    "head_step_no": "Dynamic Programming",
                    "title": "Longest Palindromic Subsequence | (DP-28)",
                    "post_link": "https://takeuforward.org/data-structure/longest-palindromic-subsequence-dp-28/",
                    "yt_link": "https://youtu.be/6i_T5kkfv4A",
                    "cs_link": "https://www.codingninjas.com/studio/problems/longest-palindromic-subsequence_842787?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/longest-palindromic-subsequence-1612327878/1",
                    "lc_link": "https://leetcode.com/problems/longest-palindromic-subsequence/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"recursion\",\"label\":\"Recursion\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "ditdistncdp33",
                    "step_no": 9,
                    "sl_no_in_step": 9,
                    "head_step_no": "Dynamic Programming",
                    "title": "Edit Distance | (DP-33)",
                    "post_link": "https://takeuforward.org/data-structure/edit-distance-dp-33/",
                    "yt_link": "https://youtu.be/fJaKO8FbDdo",
                    "cs_link": "https://www.codingninjas.com/studio/problems/shortest-common-supersequence_4244493?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/edit-distance3702/1",
                    "lc_link": "https://leetcode.com/problems/edit-distance/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                },
                {
                    "id": "byndstcksllivdp38",
                    "step_no": 9,
                    "sl_no_in_step": 10,
                    "head_step_no": "Dynamic Programming",
                    "title": "Buy and Stock Sell IV |(DP-38)",
                    "post_link": "https://takeuforward.org/data-structure/buy-and-sell-stock-iv-dp-38/",
                    "yt_link": "https://youtu.be/IV1dHbk5CDc",
                    "cs_link": "https://www.codingninjas.com/studio/problems/best-time-to-buy-and-sell-stock-iv_1080698?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/maximum-profit4657/1",
                    "lc_link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                },
                {
                    "id": "lngstincrsingsbsqnc",
                    "step_no": 9,
                    "sl_no_in_step": 11,
                    "head_step_no": "Dynamic Programming",
                    "title": "Longest Increasing Subsequence",
                    "post_link": "https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/",
                    "yt_link": "https://youtu.be/ekcwMsSIzVc",
                    "cs_link": "https://bit.ly/3GuWGpA",
                    "gfg_link": null,
                    "lc_link": "https://leetcode.com/problems/longest-increasing-subsequence/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "brstbllnsdp51",
                    "step_no": 9,
                    "sl_no_in_step": 12,
                    "head_step_no": "Dynamic Programming",
                    "title": "Burst Balloons|(DP-51)",
                    "post_link": "https://takeuforward.org/data-structure/burst-balloons-partition-dp-dp-51/",
                    "yt_link": "https://youtu.be/Yz4LlDSlkns",
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/burst-balloons_628471?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3A9LdKp",
                    "lc_link": "https://leetcode.com/problems/burst-balloons/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"dynamic-programming\",\"label\":\"Dynamic Programming\"},{\"value\":\"recursion\",\"label\":\"Recursion\"}]"
                }
            ]
        },
        {
            "step_no": 10,
            "head_step_no": "Tries",
            "topics": [
                {
                    "id": "implmnttri2prfixtr",
                    "step_no": 10,
                    "sl_no_in_step": 1,
                    "head_step_no": "Tries",
                    "title": "Implement Trie - 2 (Prefix Tree)",
                    "post_link": "https://takeuforward.org/data-structure/implement-trie-ii/",
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/studio/problems/trie-delete-operation_1062663?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3SUAiwJ",
                    "lc_link": "https://bit.ly/3qwT4OL",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"trie\",\"label\":\"Trie\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "mximmxrwithnlmntfrmrry",
                    "step_no": 10,
                    "sl_no_in_step": 2,
                    "head_step_no": "Tries",
                    "title": "Maximum XOR With an Element From Array",
                    "post_link": "https://takeuforward.org/trie/maximum-xor-queries-trie/",
                    "yt_link": "https://www.youtube.com/watch?v=Q8LhG9Pi5KM&list=PLgUwDviBIf0pcIDCZnxhv0LkHf5KzG9zp&index=7",
                    "cs_link": "https://www.codingninjas.com/studio/problems/maximum-xor-with-an-element-from-array_1382020?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://bit.ly/3tNYB3Y",
                    "lc_link": "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"bit-manipulation\",\"label\":\"Bit Manipulation\"},{\"value\":\"trie\",\"label\":\"Trie\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "nmbrfdistinctsbstringsinstring",
                    "step_no": 10,
                    "sl_no_in_step": 3,
                    "head_step_no": "Tries",
                    "title": "Number of Distinct Substrings in a String",
                    "post_link": "https://takeuforward.org/data-structure/number-of-distinct-substrings-in-a-string-using-trie/",
                    "yt_link": "https://www.youtube.com/watch?v=RV0QeTyHZxo&list=PLgUwDviBIf0pcIDCZnxhv0LkHf5KzG9zp&index=4",
                    "cs_link": "https://www.codingninjas.com/studio/problems/count-distinct-substrings_985292?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/count-of-distinct-substrings/1",
                    "lc_link": "https://bit.ly/3ocRQW0",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"trie\",\"label\":\"Trie\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        },
        {
            "step_no": 11,
            "head_step_no": "String",
            "topics": [
                {
                    "id": "minimmnmbrfbrcktrvrslsnddtmknxprssinblncd",
                    "step_no": 11,
                    "sl_no_in_step": 1,
                    "head_step_no": "String",
                    "title": "Minimum number of bracket reversals needed to make an expression balanced",
                    "post_link": null,
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/studio/problems/minimum-cost-to-make-string-valid_1115770?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/count-the-reversals0401/1",
                    "lc_link": "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/",
                    "company_tags": null,
                    "difficulty": 1,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"stack\",\"label\":\"Stack\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"},{\"value\":\"greedy\",\"label\":\"Greedy\"}]"
                },
                {
                    "id": "rbinkrp",
                    "step_no": 11,
                    "sl_no_in_step": 2,
                    "head_step_no": "String",
                    "title": "Rabin Karp",
                    "post_link": null,
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/stringmatch-rabincarp_1115738?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/31272eef104840f7430ad9fd1d43b434a4b9596b/1",
                    "lc_link": "https://leetcode.com/problems/repeated-string-match/discuss/416144/Rabin-Karp-algorithm-C%2B%2B-implementation",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "zfnctin",
                    "step_no": 11,
                    "sl_no_in_step": 3,
                    "head_step_no": "String",
                    "title": "Z-Function",
                    "post_link": null,
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/pattern-searching-using-z-algorithm_8395752?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/8dcd25918295847b4ced54055eae35a8501181c1/1",
                    "lc_link": "https://leetcode.com/problems/implement-strstr/",
                    "company_tags": null,
                    "difficulty": 0,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                },
                {
                    "id": "kmplglpspirry",
                    "step_no": 11,
                    "sl_no_in_step": 4,
                    "head_step_no": "String",
                    "title": "KMP algo / LPS(pi) array",
                    "post_link": null,
                    "yt_link": null,
                    "cs_link": "https://www.codingninjas.com/codestudio/problems/search-pattern-kmp-algorithm_8416386?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
                    "gfg_link": "https://practice.geeksforgeeks.org/problems/search-pattern0205/1",
                    "lc_link": "https://leetcode.com/problems/implement-strstr/",
                    "company_tags": null,
                    "difficulty": 2,
                    "ques_topic": "[{\"value\":\"string\",\"label\":\"String\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
                }
            ]
        }
    ]